---
- hosts: all
  become: true 
  tasks:

  - name: update repository index
    package:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php packages for Ubuntu
    package:
      name: 
       - "{{ apache_package }}"
       - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package and php packages for CentOS
    dnf:
      name: 
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
